### ISSUE TITLE
Trying to buld 6502 port fails

### ISSUE THREAD

**Issue by ssuukk** [picoos/picoos#11] opened 2020-07-06 11:10 UTC
cc65 -g -t c64 -O -T -o obj/6502/deb/picoos/src/pico/picoos.i -I. -Iinc -Iports/6502/default -Iports/6502 -D_DBG -D_POSPACK src/pico/picoos.c
src/pico/picoos.c(2678): Error: Expression expected
src/pico/picoos.c(2678): Warning: Statement has no effect
src/pico/picoos.c(2678): Error: ';' expected
src/pico/picoos.c(2678): Error: Variable identifier expected
src/pico/picoos.c(2678): Error: Undefined symbol: 't'
src/pico/picoos.c(2678): Error: Invalid lvalue in assignment
src/pico/picoos.c(2678): Warning: Converting pointer to integer without a cast
src/pico/picoos.c(2682): Error: Incompatible types
src/pico/picoos.c(2682): Error: Struct pointer expected
src/pico/picoos.c(2682): Error: Struct/union has no field named 'magic'
src/pico/picoos.c(2682): Warning: Result of comparison is constant
src/pico/picoos.c(2690): Error: Struct pointer expected
src/pico/picoos.c(2690): Error: Struct/union has no field named 'sema'
src/pico/picoos.c(2690): Error: Invalid lvalue in assignment
src/pico/picoos.c(2690): Fatal: Too many errors
make/compile.mak:252: recipe for target 'obj/6502/deb/picoos/src/pico/picoos.o' failed
make: *** [obj/6502/deb/picoos/src/pico/picoos.o] Error 1

**Comment by AriZuu** [comment] 2020-07-06 11:14
What is your compiler version ? I compiled my test project with cc65 V2.13.3 without problems.

**Comment by ssuukk** [comment] 2020-07-06 11:18
cc65 V2.18. Should I downgrade to be able to build?

**Comment by AriZuu** [comment] 2020-07-06 11:19
If you are in a hurry :-)
I'll upgrade my compiler to see what has changed.

**Comment by AriZuu** [comment] 2020-07-06 11:31
I wonder what the problem is. Upgraded compiler to 2.18 and it still compiles:

% cc65 -V
cc65 V2.18 - Git N/A
% gmake
../picoos/make/common.mak:128: Build mode not specified. Now using BUILD=DEBUG
gmake -C ../picoos/ --no-print-directory all OLIBNAME=picoos
mkdir -p /usr/home/ari/my-development/embedded/cc65-test/bin/6502-deb/obj/picoos/ports/6502/ /usr/home/ari/my-development/embedded/cc65-test/bin/6502-deb/obj/picoos/src/pico/
/home/ari/my-development/embedded/cc65/bin/cc65 -g -t c64 -O -T -o /usr/home/ari/my-development/embedded/cc65-test/bin/6502-deb/obj/picoos/src/pico/picoos.i -I. -Iinc -I/usr/home/ari/my-development/embedded/cc65-test -Iports/6502 -D_DBG -D_POSPACK src/pico/picoos.c
/home/ari/my-development/embedded/cc65/bin/ca65 -t c64 -o /usr/home/ari/my-development/embedded/cc65-test/bin/6502-deb/obj/picoos/src/pico/picoos.o -I. -Iinc -I/usr/home/ari/my-development/embedded/cc65-test -Iports/6502 -D_DBG -D_POSPACK /usr/home/ari/my-development/embedded/cc65-test/bin/6502-deb/obj/picoos/src/pico/picoos.i
rm -f /usr/home/ari/my-development/embedded/cc65-test/bin/6502-deb/obj/picoos/src/pico/picoos.i
/home/ari/my-development/embedded/cc65/bin/cc65 -g -t c64 -O -T -o /usr/home/ari/my-development/embedded/cc65-test/bin/6502-deb/obj/picoos/ports/6502/arch_c.i -I. -Iinc -I/usr/home/ari/my-development/embedded/cc65-test -Iports/6502 -D_DBG -D_POSPACK ports/6502/arch_c.c
/home/ari/my-development/embedded/cc65/bin/ca65 -t c64 -o /usr/home/ari/my-development/embedded/cc65-test/bin/6502-deb/obj/picoos/ports/6502/arch_c.o -I. -Iinc -I/usr/home/ari/my-development/embedded/cc65-test -Iports/6502 -D_DBG -D_POSPACK /usr/home/ari/my-development/embedded/cc65-test/bin/6502-deb/obj/picoos/ports/6502/arch_c.i
rm -f /usr/home/ari/my-development/embedded/cc65-test/bin/6502-deb/obj/picoos/ports/6502/arch_c.i
/home/ari/my-development/embedded/cc65/bin/ca65 -t c64 -o /usr/home/ari/my-development/embedded/cc65-test/bin/6502-deb/obj/picoos/ports/6502/arch_a.o -I. -Iinc -I/usr/home/ari/my-development/embedded/cc65-test -Iports/6502 -D_DBG -D_POSPACK ports/6502/arch_a.s
mkdir -p /usr/home/ari/my-development/embedded/cc65-test/bin/6502-deb/lib
/home/ari/my-development/embedded/cc65/bin/ar65 a /usr/home/ari/my-development/embedded/cc65-test/bin/6502-deb/lib/picoos.lib /usr/home/ari/my-development/embedded/cc65-test/bin/6502-deb/obj/picoos/src/pico/picoos.o /usr/home/ari/my-development/embedded/cc65-test/bin/6502-deb/obj/picoos/ports/6502/arch_c.o /usr/home/ari/my-development/embedded/cc65-test/bin/6502-deb/obj/picoos/ports/6502/arch_a.o
mkdir -p /usr/home/ari/my-development/embedded/cc65-test/bin/6502-deb/obj/test/
/home/ari/my-development/embedded/cc65/bin/cc65 -g -t c64 -O -T -o /usr/home/ari/my-development/embedded/cc65-test/bin/6502-deb/obj/test/test.i -I. -I../picoos/inc -I/usr/home/ari/my-development/embedded/cc65-test -I../picoos/ports/6502 -D_DBG -D_POSPACK test.c
/home/ari/my-development/embedded/cc65/bin/ca65 -t c64 -o /usr/home/ari/my-development/embedded/cc65-test/bin/6502-deb/obj/test/test.o -I. -I../picoos/inc -I/usr/home/ari/my-development/embedded/cc65-test -I../picoos/ports/6502 -D_DBG -D_POSPACK /usr/home/ari/my-development/embedded/cc65-test/bin/6502-deb/obj/test/test.i
rm -f /usr/home/ari/my-development/embedded/cc65-test/bin/6502-deb/obj/test/test.i
mkdir -p /usr/home/ari/my-development/embedded/cc65-test/bin/6502-deb/out
/home/ari/my-development/embedded/cc65/bin/ld65 -t c64 -Ln /usr/home/ari/my-development/embedded/cc65-test/bin/6502-deb/out/test.lbl -m /usr/home/ari/my-development/embedded/cc65-test/bin/6502-deb/out/test.map -o /usr/home/ari/my-development/embedded/cc65-test/bin/6502-deb/out/test.c64  /usr/home/ari/my-development/embedded/cc65-test/bin/6502-deb/obj/test/test.o  /usr/home/ari/my-development/embedded/cc65-test/bin/6502-deb/lib/picoos.lib c64.lib

**Comment by ssuukk** [comment] 2020-07-06 11:33
Hmmm... Any particular way/branch to clone? I did just "git clone https://github.com/picoos/picoos.git"

**Comment by ssuukk** [comment] 2020-07-06 11:42
Ah, wait. You're using gmake, I'll try this instead of make... I don't see you passing PORT-6502, though.

**Comment by AriZuu** [comment] 2020-07-06 11:53
Seems to be related to POSCFG_FEATURE_TIMER. My test code didn't use that. I'll do some more digging.

**Comment by AriZuu** [comment] 2020-07-06 12:47
Ok... The posTimerSet expands to something like this, ie. P_ASSERT expands to "do {} while (0)" because it is not used in this port. For some reason, the compiler doesn't like that (but seems to like it earlier in the source code. A bit confusing, I might say.

```c
typedef struct
{
  struct
  {
    int magic;
  } e;

} *EVENT_t;

typedef struct
{
  int magic;
  int x;
} TIMER_t;

int func (void *sema, void *tmr)
{
  register EVENT_t ev = (EVENT_t) sema;
  do { } while (0);

  if (((ev) == ((void *) 0)) || (ev->e.magic != 0x53))
    return (-3);

  register TIMER_t *t = (TIMER_t *) tmr;

  do { } while (0);
  do { } while (0);

  if (((t) == ((void *) 0)) || (t->magic != 0x14))
    return (-3);

  __asm__ ("php");
  __asm__ ("sei");
  __asm__ ("plp");

  return 0;
}

```

**Comment by AriZuu** [comment] 2020-07-06 12:52
Would be great If someone knowing cc65 compiler better could help with above snipped to compile.

**Comment by ssuukk** [comment] 2020-07-06 13:00
Don't look at me. I hardly know C and can't really imagine how a STANDARDISED language can't properly compile in a different compiler! :D

**Comment by AriZuu** [comment] 2020-07-06 13:11
I think I figured it out. Could you please pull cc65-fix branch and test ?

**Comment by ssuukk** [comment] 2020-07-06 13:30
Sure, just a moment.

**Comment by ssuukk** [comment] 2020-07-06 13:39
It seems it compiles!

qus@qus-VirtualBox:~/dev/picoos$ make PORT=6502
make/common.mak:128: Build mode not specified. Now using BUILD=DEBUG
/home/qus/cc65/bin/cc65 -g -t c64 -O -T -o obj/6502/deb/picoos/src/pico/picoos.i -I. -Iinc -Iports/6502/default -Iports/6502 -D_DBG -D_POSPACK src/pico/picoos.c
/home/qus/cc65/bin/ca65 -t c64 -o obj/6502/deb/picoos/src/pico/picoos.o -I. -Iinc -Iports/6502/default -Iports/6502 -D_DBG -D_POSPACK obj/6502/deb/picoos/src/pico/picoos.i
rm -f obj/6502/deb/picoos/src/pico/picoos.i
/home/qus/cc65/bin/cc65 -g -t c64 -O -T -o obj/6502/deb/picoos/ports/6502/arch_c.i -I. -Iinc -Iports/6502/default -Iports/6502 -D_DBG -D_POSPACK ports/6502/arch_c.c
/home/qus/cc65/bin/ca65 -t c64 -o obj/6502/deb/picoos/ports/6502/arch_c.o -I. -Iinc -Iports/6502/default -Iports/6502 -D_DBG -D_POSPACK obj/6502/deb/picoos/ports/6502/arch_c.i
rm -f obj/6502/deb/picoos/ports/6502/arch_c.i
/home/qus/cc65/bin/ca65 -t c64 -o obj/6502/deb/picoos/ports/6502/arch_a.o -I. -Iinc -Iports/6502/default -Iports/6502 -D_DBG -D_POSPACK ports/6502/arch_a.s
mkdir -p lib
mkdir -p lib/6502
mkdir -p lib/6502/deb
/home/qus/cc65/bin/ar65 a lib/6502/deb/picoos.lib obj/6502/deb/picoos/src/pico/picoos.o obj/6502/deb/picoos/ports/6502/arch_c.o obj/6502/deb/picoos/ports/6502/arch_a.o 

That's some instand tech support! ;)

**Comment by AriZuu** [comment] 2020-07-06 15:18
Thanks for testing, fix is now merged to master.

**Closed by AriZuu** 2020-07-06 15:18 UTC
